### ISSUE TITLE
Lockup in ffmpeg with h264_omx encoder

### ISSUE THREAD

**Issue by 6by9** [raspberrypi/firmware#1185]
From @devalexqt in https://github.com/raspberrypi/firmware/issues/1087#issuecomment-510226184

My configuration:
Raspberry Pi 3 B v1.2 (with latest firmware) + Raspberry Pi Camera v1.3
```
uname -a
Linux raspberrypi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
```
First I try to build latest version of ffmpeg from git but it freeze as this thread say then I try to install latest version of ffmpeg from raspbian repository via "sudo apt-get install ffmpeg" and it installs ffmpeg version 3.2.14-1~deb9u1+rpt1 and it still freeze.

I know that I can get h264 from raspivid, but run command with raw video in yuv420p format from raspivid stdout is likely for quick reproduce of the bug because encoder was freeze on 2 seconds.

In my case I need two output files from pi camera, one is video in mp4 container and second output must be series of jpeg images for every seconds of video for analysis in other software, like motion detection. So, my real command is below:

ffmpeg -f video4linux2 -pixel_format yuv420p -input_format yuv420p -video_size 1920x1080 -framerate 30 -i /dev/video0 -threads 4 -filter_complex '[0:V]split=2[video][s2];[s2]fps=1,scale=1920:1080[img]' -map [video] -c:v h264_omx  -an -b:v 6M  -y webcam.mp4 -map [img] -f image2 -y img/output_%03d.jpg

But it still freeze at random run time, for example: 1 minute, 24 minutes or 1 h, etc. I try different run commands for ffmpeg but result it stay the same => freeze and in same cases it may cause OS to freeze too.
I think it a same bug.

**Comment by tmm1** [comment]
I'm experiencing a lock-up in ffmpeg's h264_omx that occurs with zerocopy disabled, happening randomly after 100-500 frames have been encoded. This is happening even _after_ https://github.com/FFmpeg/FFmpeg/commit/3d857f219eb972fb345e784d17268e16b6dec6f0 was applied.

```
Thread 15 (Thread 0x6c0fb460 (LWP 2541)):
#0  0x76f1d088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1,
    futex_word=0xb8ab5c) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0xb8ab5c, abstime=0x0) at sem_waitcommon.c:115
#2  0x76f1d1f4 in __new_sem_wait_slow (sem=0xb8ab5c, abstime=0x0) at sem_waitcommon.c:282
#3  0x6eac1b60 in vchiu_queue_pop () from /opt/vc/lib/libvchiq_arm.so
#4  0x6ea90d70 in ilcs_task () from /opt/vc/lib/libopenmaxil.so
#5  0x6eaa6cb0 in vcos_thread_entry (arg=0xb8aa18)
    at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#6  0x76f13494 in start_thread (arg=0x6c0fb460) at pthread_create.c:486
#7  0x76e6c578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
   from /lib/arm-linux-gnueabihf/libc.so.6

Thread 14 (Thread 0x6c8fc460 (LWP 2540)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0xb8a9f0)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0xb8a9c8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0xb8a9c8, mutex=0x0, mutex@entry=0xb8a9ac)
    at pthread_cond_wait.c:655
#3  0x6eaa6d94 in _timer_thread (arg=0xb8a9a8)
    at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:722
#4  0x76f13494 in start_thread (arg=0x6c8fc460) at pthread_create.c:486
#5  0x76e6c578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
   from /lib/arm-linux-gnueabihf/libc.so.6

Thread 13 (Thread 0x6d0fd460 (LWP 2539)):
#0  0x76f1d088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1,
    futex_word=0x6eafab7c <cecservice_notify_available_event+24>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x6eafab7c <cecservice_notify_available_event+24>, abstime=0x0)
    at sem_waitcommon.c:115
#2  0x76f1d1f4 in __new_sem_wait_slow (sem=0x6eafab7c <cecservice_notify_available_event+24>,
    abstime=0x0) at sem_waitcommon.c:282
#3  0x6eae0ffc in cecservice_notify_func () from /opt/vc/lib/libbcm_host.so
#4  0x6eaa6cb0 in vcos_thread_entry (arg=0x6eafab90 <cecservice_notify_task>)
    at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#5  0x76f13494 in start_thread (arg=0x6d0fd460) at pthread_create.c:486
#6  0x76e6c578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
   from /lib/arm-linux-gnueabihf/libc.so.6

Thread 12 (Thread 0x6d8fe460 (LWP 2538)):
#0  0x76f1d088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1,
    futex_word=0x6eaf9dec <tvservice_notify_available_event+24>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x6eaf9dec <tvservice_notify_available_event+24>, abstime=0x0)
    at sem_waitcommon.c:115
#2  0x76f1d1f4 in __new_sem_wait_slow (sem=0x6eaf9dec <tvservice_notify_available_event+24>,
    abstime=0x0) at sem_waitcommon.c:282
#3  0x6eadfc8c in tvservice_notify_func () from /opt/vc/lib/libbcm_host.so
#4  0x6eaa6cb0 in vcos_thread_entry (arg=0x6eaf9e00 <tvservice_notify_task>)
    at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#5  0x76f13494 in start_thread (arg=0x6d8fe460) at pthread_create.c:486
#6  0x76e6c578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
   from /lib/arm-linux-gnueabihf/libc.so.6

Thread 11 (Thread 0x6e0ff460 (LWP 2537)):
#0  0x76f1d088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1,
    futex_word=0x6eafac78 <dispmanx_notify_available_event+24>)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x6eafac78 <dispmanx_notify_available_event+24>, abstime=0x0)
    at sem_waitcommon.c:115
#2  0x76f1d1f4 in __new_sem_wait_slow (sem=0x6eafac78 <dispmanx_notify_available_event+24>, abstime=0x0)
    at sem_waitcommon.c:282
#3  0x6eae3db0 in dispmanx_notify_func () from /opt/vc/lib/libbcm_host.so
#4  0x6eaa6cb0 in vcos_thread_entry (arg=0x6eafb9b8 <dispmanx_notify_task>)
    at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#5  0x76f13494 in start_thread (arg=0x6e0ff460) at pthread_create.c:486
#6  0x76e6c578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
   from /lib/arm-linux-gnueabihf/libc.so.6

Thread 10 (Thread 0x6ea2f460 (LWP 2536)):
#0  0x76e6451c in ioctl () at ../sysdeps/unix/syscall-template.S:78
#1  0x6eabf010 in completion_thread () from /opt/vc/lib/libvchiq_arm.so
#2  0x6eaa6cb0 in vcos_thread_entry (arg=0x6ead2318 <vchiq_instance+16>)
    at /home/dom/projects/staging/userland/interface/vcos/pthreads/vcos_pthreads.c:144
#3  0x76f13494 in start_thread (arg=0x6ea2f460) at pthread_create.c:486
#4  0x76e6c578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73
   from /lib/arm-linux-gnueabihf/libc.so.6
```
