### ISSUE TITLE
GStream (v1.18.4) SIGSEGVwith rpicamsrc on Raspbian 64B Bulleye (Raspberry 4)

### ISSUE THREAD

**Issue by Topper69** [raspberrypi/firmware#1780]
**Is this the right place for my bug report?**

**Describe the bug**
Using updated raspbian bulleseye 64b on raspberry pi 4 && camera module 2 noir, launching gstream pipeline with libcamerasrc like:
gst-launch-1.0 libcamerasrc ! video/x-raw, width=640, height=480, framerate=30/1 ! videoconvert ! videoscale ! clockoverlay time-format="%D %H:%M:%S" ! autovideosink
sig fault.
...
[2:09:45.235713512] [3827] DEBUG RPI raspberrypi.cpp:851 Stream ISP Output0 has color space Rec709
[2:09:45.235765919] [3827] DEBUG RPI raspberrypi.cpp:917 Setting ISP Output1 (internal) to 320x240-YU12
Caught SIGSEGV
#0 0x0000007f86f6cef4 in __GI___poll
#1 0x0000007f8710adf8 in () at /lib/aarch64-linux-gnu/libglib-2.0.so.0
#2 0x0000007f8710b1b0 in g_main_loop_run ()
#3 0x000000558ed4424c in ()
#4 0x0000007f86ec4e18 in __libc_start_main (main=
#5 0x000000558ed44368 in _start ()
Spinning. Please run 'gdb gst-launch-1.0 3824' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.

**To reproduce**
gst-launch-1.0 libcamerasrc ! video/x-raw, width=640, height=480, framerate=30/1 ! videoconvert ! videoscale ! clockoverlay time-format="%D %H:%M:%S" ! autovideosink
Every pipeline used with libcamerasrc failed.
gstreamer with videotestsrc video is working fine. Libcamera and camera is working fine with other app.

**Expected behaviour**
Should not sigfautl.

**Actual behaviour**
Sigfault.

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:
https://pastebin.com/NLHetTW5

* Which model of Raspberry Pi? PI4B-8G
* Which OS and version (`cat /etc/rpi-issue`)? Bulleseye
* Which firmware version (`vcgencmd version`)? 658f02cc8edcb68a568273f05d2b6ceede181e15
* Which kernel version (`uname -a`)? Linux raspberrypi-8G 5.15.89-v8+ #1621 SMP PREEMPT Tue Jan 24 11:12:35 GMT 2023 aarch64 GNU/Linux

**Logs**
If applicable, add the relevant output from `dmesg` or similar.
full backtrace:
Définition du pipeline à PAUSED...
[2:09:45.174807915] [3824] INFO Camera camera_manager.cpp:299 libcamera v0.0.2+55-5df5b72c
[2:09:45.222197503] [3827] WARN RPiController controller.cpp:43 This format of the tuning file will be deprecated soon! Please use the convert_tuning.py utility to update to version 2.0.
[2:09:45.222291057] [3827] WARN RPiController controller.cpp:80 No algorithm found for "version"
[2:09:45.222314390] [3827] WARN RPiController controller.cpp:80 No algorithm found for "target"
[2:09:45.222335130] [3827] WARN RPiController controller.cpp:80 No algorithm found for "algorithms"
[2:09:45.223267967] [3827] WARN RPI raspberrypi.cpp:1308 Mismatch between Unicam and CamHelper for embedded data usage!
[2:09:45.224176712] [3827] DEBUG RPiDelayedControls delayed_controls.cpp:103 Set a delay of 2 and priority write flag 0 for Horizontal Blanking
[2:09:45.224233674] [3827] DEBUG RPiDelayedControls delayed_controls.cpp:103 Set a delay of 2 and priority write flag 1 for Vertical Blanking
[2:09:45.224257766] [3827] DEBUG RPiDelayedControls delayed_controls.cpp:103 Set a delay of 2 and priority write flag 0 for Exposure
[2:09:45.224279970] [3827] DEBUG RPiDelayedControls delayed_controls.cpp:103 Set a delay of 1 and priority write flag 0 for Analogue Gain
[2:09:45.224385357] [3827] INFO RPI raspberrypi.cpp:1425 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media3 and ISP device /dev/media0
[2:09:45.224430541] [3827] DEBUG RPI raspberrypi.cpp:1204 Unable to acquire a Unicam instance
Le pipeline est actif et n’a pas besoin de phase PREROLL…
[2:09:45.226358696] [3828] DEBUG RPI raspberrypi.cpp:576 Try color space Rec709
Le pipeline a terminé la phase PREROLL…
Passage du pipeline à la phase PLAYING…
New clock: GstSystemClock
[2:09:45.233309846] [3828] DEBUG RPI raspberrypi.cpp:576 Try color space Rec709
[2:09:45.233520954] [3828] DEBUG RPI raspberrypi.cpp:576 Try color space Rec709
[2:09:45.233567213] [3828] INFO Camera camera.cpp:1026 configuring streams: (0) 640x480-NV21
[2:09:45.233746099] [3827] DEBUG RPI raspberrypi.cpp:168 Format: 640x480 fmt SRGGB10 Score: 1000 (best 1000)
[2:09:45.233849153] [3827] DEBUG RPI raspberrypi.cpp:168 Format: 1640x1232 fmt SRGGB10 Score: 1444.49 (best 1000)
[2:09:45.233897911] [3827] DEBUG RPI raspberrypi.cpp:168 Format: 1920x1080 fmt SRGGB10 Score: 1636.67 (best 1000)
[2:09:45.233943114] [3827] DEBUG RPI raspberrypi.cpp:168 Format: 3280x2464 fmt SRGGB10 Score: 2162.49 (best 1000)
[2:09:45.233989965] [3827] DEBUG RPI raspberrypi.cpp:168 Format: 640x480 fmt SRGGB8 Score: 2000 (best 1000)
[2:09:45.234035872] [3827] DEBUG RPI raspberrypi.cpp:168 Format: 1640x1232 fmt SRGGB8 Score: 2444.49 (best 1000)
[2:09:45.234168499] [3827] DEBUG RPI raspberrypi.cpp:168 Format: 1920x1080 fmt SRGGB8 Score: 2636.67 (best 1000)
[2:09:45.234230387] [3827] DEBUG RPI raspberrypi.cpp:168 Format: 3280x2464 fmt SRGGB8 Score: 3162.49 (best 1000)
[2:09:45.234418662] [3827] INFO RPI raspberrypi.cpp:805 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected sensor format: 640x480-SBGGR10_1X10 - Selected unicam format: 640x480-pBAA
[2:09:45.235224298] [3827] DEBUG RPI raspberrypi.cpp:837 Setting ISP Output0 to 640x480-NV21
[2:09:45.235713512] [3827] DEBUG RPI raspberrypi.cpp:851 Stream ISP Output0 has color space Rec709
[2:09:45.235765919] [3827] DEBUG RPI raspberrypi.cpp:917 Setting ISP Output1 (internal) to 320x240-YU12
Caught SIGSEGV
#0 0x0000007f86f6cef4 in __GI___poll
#1 0x0000007f8710adf8 in () at /lib/aarch64-linux-gnu/libglib-2.0.so.0
#2 0x0000007f8710b1b0 in g_main_loop_run ()
#3 0x000000558ed4424c in ()
#4 0x0000007f86ec4e18 in __libc_start_main (main=
#5 0x000000558ed44368 in _start ()
Spinning. Please run 'gdb gst-launch-1.0 3824' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
^Chandling interrupt.
Interruption : arrêt du pipeline…
Execution ended after 0:00:03.963971512
Définition du pipeline à NULL…

**Additional context**
Add any other relevant context for the problem.

**Comment by Topper69** [comment]
Fixed after an rpi-update to lastest firmware.
